/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Get Suggestions Schema
 *   version: 2023-10-31
 */

import { z, lazySchema } from '@kbn/zod/v4';

import { SuccessResponse } from '../model/schema/common.gen';

export const GetEndpointSuggestionsRequestParams = lazySchema(() =>
  z.object({
    suggestion_type: z.enum([
      'eventFilters',
      'endpoints',
      'endpointExceptions',
      'trustedApps',
      'trustedDevices',
    ]),
  })
);
export type GetEndpointSuggestionsRequestParams = z.infer<
  typeof GetEndpointSuggestionsRequestParams
>;
export type GetEndpointSuggestionsRequestParamsInput = z.input<
  typeof GetEndpointSuggestionsRequestParams
>;

export const GetEndpointSuggestionsRequestBody = lazySchema(() =>
  z.object({
    /**
     * ECS field path for autocomplete suggestions.
     */
    field: z.string().max(256),
    /**
     * Autocomplete prefix query string.
     */
    query: z.string().max(1024),
    /**
     * Elasticsearch filter clauses. Runtime validation in get_suggestions.ts enforces key count, array item count, and string lengths; the generated schema only bounds top-level array size.
     */
    filters: z.array(z.object({}).catchall(z.unknown())).max(50).optional(),
    /**
     * Field metadata map. Runtime validation in get_suggestions.ts enforces a maximum of 50 keys and per-key string lengths; the generated schema only bounds value types.
     */
    fieldMeta: z
      .object({})
      .catchall(z.union([z.string().max(10000), z.number(), z.boolean()]))
      .optional(),
  })
);
export type GetEndpointSuggestionsRequestBody = z.infer<typeof GetEndpointSuggestionsRequestBody>;
export type GetEndpointSuggestionsRequestBodyInput = z.input<
  typeof GetEndpointSuggestionsRequestBody
>;

export const GetEndpointSuggestionsResponse = lazySchema(() => SuccessResponse);
export type GetEndpointSuggestionsResponse = z.infer<typeof GetEndpointSuggestionsResponse>;
