/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Endpoint Management API client for tests
 *   version: Bundle (no version)
 */

import supertest_ from 'supertest';
import type SuperTest from 'supertest';
import { format as formatUrl } from 'url';
import {
  ELASTIC_HTTP_VERSION_HEADER,
  X_ELASTIC_INTERNAL_ORIGIN_REQUEST,
} from '@kbn/core-http-common';
import { replaceParams } from '@kbn/openapi-common/shared';

import type {
  CreateUpdateProtectionUpdatesNoteRequestParamsInput,
  CreateUpdateProtectionUpdatesNoteRequestBodyInput,
  GetProtectionUpdatesNoteRequestParamsInput,
} from '@kbn/security-solution-plugin/common/api/endpoint/protection_updates_note/protection_updates_note.gen';
import type { GetEndpointMetadataListRequestQueryInput } from '@kbn/security-solution-plugin/common/api/endpoint/metadata/get_metadata.gen';
import type {
  GetEndpointSuggestionsRequestParamsInput,
  GetEndpointSuggestionsRequestBodyInput,
} from '@kbn/security-solution-plugin/common/api/endpoint/suggestions/get_suggestions.gen';
import type { GetPolicyResponseRequestQueryInput } from '@kbn/security-solution-plugin/common/api/endpoint/policy/policy_response.gen';

import type { FtrProviderContext } from '@kbn/ftr-common-functional-services';
import { getRouteUrlForSpace } from '@kbn/spaces-plugin/common';

const securitySolutionApiServiceFactory = (supertest: SuperTest.Agent) => ({
  /**
   * Create or update the protection updates note for a package policy.
   */
  createUpdateProtectionUpdatesNote(
    props: CreateUpdateProtectionUpdatesNoteProps,
    kibanaSpace: string = 'default'
  ) {
    return supertest
      .post(
        getRouteUrlForSpace(
          replaceParams('/api/endpoint/protection_updates_note/{package_policy_id}', props.params),
          kibanaSpace
        )
      )
      .set('kbn-xsrf', 'true')
      .set(ELASTIC_HTTP_VERSION_HEADER, '2023-10-31')
      .set(X_ELASTIC_INTERNAL_ORIGIN_REQUEST, 'kibana')
      .send(props.body as object);
  },
  getEndpointExceptionsPerPolicyOptIn(kibanaSpace: string = 'default') {
    return supertest
      .get(
        getRouteUrlForSpace(
          '/internal/api/endpoint/endpoint_exceptions_per_policy_opt_in',
          kibanaSpace
        )
      )
      .set('kbn-xsrf', 'true')
      .set(ELASTIC_HTTP_VERSION_HEADER, '1')
      .set(X_ELASTIC_INTERNAL_ORIGIN_REQUEST, 'kibana');
  },
  /**
   * Get a list of all endpoint host metadata.
   */
  getEndpointMetadataList(props: GetEndpointMetadataListProps, kibanaSpace: string = 'default') {
    return supertest
      .get(getRouteUrlForSpace('/api/endpoint/metadata', kibanaSpace))
      .set('kbn-xsrf', 'true')
      .set(ELASTIC_HTTP_VERSION_HEADER, '2023-10-31')
      .set(X_ELASTIC_INTERNAL_ORIGIN_REQUEST, 'kibana')
      .query(props.query);
  },
  getEndpointSuggestions(props: GetEndpointSuggestionsProps, kibanaSpace: string = 'default') {
    return supertest
      .post(
        getRouteUrlForSpace(
          replaceParams('/internal/api/endpoint/suggestions/{suggestion_type}', props.params),
          kibanaSpace
        )
      )
      .set('kbn-xsrf', 'true')
      .set(ELASTIC_HTTP_VERSION_HEADER, '2023-10-31')
      .set(X_ELASTIC_INTERNAL_ORIGIN_REQUEST, 'kibana')
      .send(props.body as object);
  },
  /**
   * Get the most recent policy response for an endpoint.
   */
  getPolicyResponse(props: GetPolicyResponseProps, kibanaSpace: string = 'default') {
    return supertest
      .get(getRouteUrlForSpace('/api/endpoint/policy_response', kibanaSpace))
      .set('kbn-xsrf', 'true')
      .set(ELASTIC_HTTP_VERSION_HEADER, '2023-10-31')
      .set(X_ELASTIC_INTERNAL_ORIGIN_REQUEST, 'kibana')
      .query(props.query);
  },
  /**
   * Get the protection updates note for a package policy.
   */
  getProtectionUpdatesNote(props: GetProtectionUpdatesNoteProps, kibanaSpace: string = 'default') {
    return supertest
      .get(
        getRouteUrlForSpace(
          replaceParams('/api/endpoint/protection_updates_note/{package_policy_id}', props.params),
          kibanaSpace
        )
      )
      .set('kbn-xsrf', 'true')
      .set(ELASTIC_HTTP_VERSION_HEADER, '2023-10-31')
      .set(X_ELASTIC_INTERNAL_ORIGIN_REQUEST, 'kibana');
  },
  performEndpointExceptionsPerPolicyOptIn(kibanaSpace: string = 'default') {
    return supertest
      .post(
        getRouteUrlForSpace(
          '/internal/api/endpoint/endpoint_exceptions_per_policy_opt_in',
          kibanaSpace
        )
      )
      .set('kbn-xsrf', 'true')
      .set(ELASTIC_HTTP_VERSION_HEADER, '1')
      .set(X_ELASTIC_INTERNAL_ORIGIN_REQUEST, 'kibana');
  },
});

export function SecuritySolutionApiProvider({ getService }: FtrProviderContext) {
  const supertestService = getService('supertest');
  const config = getService('config');

  return {
    ...securitySolutionApiServiceFactory(supertestService),
    withUser: (user: { username: string; password?: string }) => {
      const kbnUrl = formatUrl({ ...config.get('servers.kibana'), auth: false });

      return securitySolutionApiServiceFactory(
        supertest_.agent(kbnUrl).auth(user.username, user.password ?? 'changeme')
      );
    },
  };
}

export interface CreateUpdateProtectionUpdatesNoteProps {
  params: CreateUpdateProtectionUpdatesNoteRequestParamsInput;
  body: CreateUpdateProtectionUpdatesNoteRequestBodyInput;
}
export interface GetEndpointMetadataListProps {
  query: GetEndpointMetadataListRequestQueryInput;
}
export interface GetEndpointSuggestionsProps {
  params: GetEndpointSuggestionsRequestParamsInput;
  body: GetEndpointSuggestionsRequestBodyInput;
}
export interface GetPolicyResponseProps {
  query: GetPolicyResponseRequestQueryInput;
}
export interface GetProtectionUpdatesNoteProps {
  params: GetProtectionUpdatesNoteRequestParamsInput;
}
